export { default as UserActivities } from './bookings/userActivities/userActivities'
export { default as DiscountOffers } from './bookings/discountOffers/discountOffers'
export { default as DatePicker } from './bookings/datePicker/datePicker'
export { default as User } from './bookings/user/user'
export { default as Table } from './bookings/table/table'
